/*
genai generates Go code from the GS1 Application Identifier syntax dictionary
at https://github.com/gs1/gs1-syntax-dictionary/blob/main/gs1-syntax-dictionary.txt
*/
package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

// Regex to parse the important parts out of the spec, namely: the AI (or
// range of AIs), whether it's fixed length (indicated by '*'), its length (if
// there's no '*' and only if there's only one component) and its title:
//
// AI  Flags  Specification     Attributes                       Title
// 01  *?     N14,csum,gcppos2  ex=255,37 dlpkey=22,10,21|235  # GTIN
// ^^  ^      ^^^                                                ^^^^
var lineRE = regexp.MustCompile(`^(\d+(?:-\d+)?) +([*?]*) +[NXYZ](?:(\d+)|\.\.\d+).+?(?:# (.*))?$`)

const header = `// Generated by ./cmd/genai; DO NOT EDIT.
//go:generate go run ./cmd/genai -i gs1-syntax-dictionary.txt -o ais.go

package gs1

type AIDesc struct {
	AI     string
	Title  string // optional
	Length int    // 0 if not fixed length
}

var ApplicationIdentifiers = map[string]AIDesc{
`

const footer = `}
`

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "genai: %s\n", err)
		os.Exit(1)
	}
}

func run() (retErr error) {
	inputPath := flag.String("i", "-", "input file")
	outputPath := flag.String("o", "-", "output file")
	flag.Parse()
	input := os.Stdin
	output := os.Stdout
	if *inputPath != "-" {
		var err error
		input, err = os.Open(*inputPath)
		if err != nil {
			return fmt.Errorf("input file: %w", err)
		}
		defer func() { _ = input.Close() }()
	}
	if *outputPath != "-" {
		var err error
		output, err = os.Create(*outputPath)
		if err != nil {
			return fmt.Errorf("output file: %w", err)
		}
		defer func() {
			retErr = errors.Join(retErr, output.Close())
		}()
	}

	scanner := bufio.NewScanner(input)
	_, _ = fmt.Fprintf(output, header)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		var ai, flags, spec, title string
		if m := lineRE.FindStringSubmatch(line); m != nil {
			ai, flags, spec, title = m[1], m[2], m[3], m[4]
		} else {
			return fmt.Errorf("unrecognised spec line: %q", line)
		}
		length := 0
		var err error
		if isFixedLength := strings.Contains(flags, "*"); isFixedLength {
			length, err = strconv.Atoi(spec)
			if err != nil {
				return fmt.Errorf("line %q: parse AI range start: %w", line, err)
			}
		}
		startStr, endStr, isRange := strings.Cut(ai, "-")
		start, _ := strconv.Atoi(startStr)
		end := start
		if isRange {
			end, err = strconv.Atoi(endStr)
			if err != nil {
				return fmt.Errorf("line %q: parse AI range end: %w", line, err)
			}
		}
		for i := start; i <= end; i++ {
			ai := fmt.Sprintf("%0*d", len(startStr), i)
			_, _ = fmt.Fprintf(output, "\t%q: {AI: %q", ai, ai)
			if title != "" {
				_, _ = fmt.Fprintf(output, ", Title: %q", title)
			}
			if length != 0 {
				_, _ = fmt.Fprintf(output, ", Length: %d", length)
			}
			_, _ = fmt.Fprintf(output, "},\n")
		}
	}
	_, _ = fmt.Fprintf(output, footer)
	return scanner.Err()
}
